from __future__ import annotations
from typing import Protocol, List
from...kernel.world.events import Event

class EventLogRepository(Protocol):
    def append(self, event: Event) -> None:...
    def list_for_tenant(self, tenant_id: str) -> List[Event]:...
    def list_all(self) -> List[Event]:...